apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "application.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "application.fullname" . }}
